import cv2 as cv

# To read videos from camera or from a file, cv.VideoCapture() method is used.

# Setting up camera to read from. 
cam_feed = cv.VideoCapture(0)           # default camera is at device index 0, multiple external cameras will be indexed from 1
# cam_feed is now the object for our camera

while True:             # since videos have continuous frames of data we need to iterate continuously to read the next frame
    ret, frame = cam_feed.read()
    # VideoCapture_object.read() method reads from the camera via the object created of it and returns a tuple containing two values.
    # First value contains True or False based on the accessibility of the camera, i.e. if camera is available it returns True else False
    # Second value contains the frame basically the pixel values in a matrix.

    # To display, we use the same method that is used for an image.
    if ret==True:
        cv.imshow('Live Cam', frame)
    else:
        print("Error Accessing Camera")
        break

    if cv.waitKey(1) & 0xFF == ord('q'):
        break

cam_feed.release()              # after using the camera object it is mandatory to release those services
cv.destroyAllWindows()          # destroys all the windows generated by cv
